// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcsmREWJ2yILNtySJTR_t9_56cW36rkRg',
    appId: '1:374033040982:web:68db2e6909fabbdf4dddf7',
    messagingSenderId: '374033040982',
    projectId: 'nonelist-7397b',
    authDomain: 'nonelist-7397b.firebaseapp.com',
    storageBucket: 'nonelist-7397b.appspot.com',
    measurementId: 'G-YYFF1SCJM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDod9yTptIznuKdzzdslC5zsl06STsM9ik',
    appId: '1:374033040982:android:824537fc219ce2ee4dddf7',
    messagingSenderId: '374033040982',
    projectId: 'nonelist-7397b',
    storageBucket: 'nonelist-7397b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBIp4btpNw5H_-B66AtYt5Ex5M-ascXus',
    appId: '1:374033040982:ios:7cc2ee5850a3e89c4dddf7',
    messagingSenderId: '374033040982',
    projectId: 'nonelist-7397b',
    storageBucket: 'nonelist-7397b.appspot.com',
    iosBundleId: 'com.notelist.app',
  );
}
